spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.10.100:3306/betta?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  #禁止项目启动时运行JOB
  batch:
    #    initialize-schema: always
    job:
      enabled: false
corn:
  path:
    backup: E:/备份/backup
    #lucene索引目录
    index: /root/file/index
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:corn/mapper/xml/*Mapper.xml