corn:
  apiUrl: http://112.74.167.183:8082
  resourceUrl: http://112.74.167.183:8082/upload/

#spring:
#  datasource:
#    url: jdbc:mysql://42.192.15.59:3306/betta?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
#    username: corn
#    password: corn2020!@#
#    driver-class-name: com.mysql.cj.jdbc.Driver